name: Deploy
on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 0 * * *" # Daily at midnight.

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Build site
        run: uv run python ./src/main.py

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - uses: actions/deploy-pages@v4
        id: deployment
